import { NextResponse } from "next/server";
import { createServerClient } from "@/lib/supabase/client";

/* GET /api/trade-in/receipts?inquiry_id=xxx */
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const inquiryId = searchParams.get("inquiry_id");
  if (!inquiryId) return NextResponse.json({ error: "inquiry_id required" }, { status: 400 });

  const supabase = createServerClient();
  const { data, error } = await supabase
    .from("trade_in_receipts")
    .select("*, trade_in_receipt_items(*)")
    .eq("inquiry_id", inquiryId)
    .order("created_at", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data);
}

/* POST /api/trade-in/receipts — create draft receipt */
export async function POST(req: Request) {
  const body = await req.json();
  const { inquiry_id, offer_id, store_location_id, seller_name, seller_address, seller_postal_city, seller_phone, seller_email, seller_bank_reg, seller_bank_account, buyer_address, buyer_postal_city, buyer_phone, delivery_method, staff_initials, items } = body;

  if (!seller_name) {
    return NextResponse.json({ error: "seller_name required" }, { status: 400 });
  }
  if (!items || !Array.isArray(items) || items.length === 0) {
    return NextResponse.json({ error: "At least one item required" }, { status: 400 });
  }

  const supabase = createServerClient();

  // Calculate total from items
  const totalAmount = items.reduce((sum: number, item: { price: number }) => sum + item.price, 0);

  // Create receipt (receipt_number auto-generated by DB default)
  const { data: receipt, error: receiptErr } = await supabase
    .from("trade_in_receipts")
    .insert({
      inquiry_id: inquiry_id || null,
      offer_id: offer_id || null,
      store_location_id: store_location_id || null,
      seller_name,
      seller_address: seller_address || null,
      seller_postal_city: seller_postal_city || null,
      seller_phone: seller_phone || null,
      seller_email: seller_email || null,
      seller_bank_reg: seller_bank_reg || null,
      seller_bank_account: seller_bank_account || null,
      buyer_address: buyer_address || null,
      buyer_postal_city: buyer_postal_city || null,
      buyer_phone: buyer_phone || null,
      total_amount: totalAmount,
      delivery_method: delivery_method || null,
      staff_initials: staff_initials || null,
    })
    .select()
    .single();

  if (receiptErr || !receipt) {
    return NextResponse.json({ error: receiptErr?.message || "Failed to create receipt" }, { status: 500 });
  }

  // Insert items
  const itemRows = items.map((item: any) => ({
    receipt_id: receipt.id,
    imei_serial: item.imei_serial || null,
    brand: item.brand,
    model: item.model,
    storage: item.storage || null,
    ram: item.ram || null,
    condition_grade: item.condition_grade || null,
    color: item.color || null,
    condition_notes: item.condition_notes || null,
    price: item.price,
  }));

  const { error: itemsErr } = await supabase
    .from("trade_in_receipt_items")
    .insert(itemRows);

  if (itemsErr) {
    // Cleanup: delete the receipt if items failed
    await supabase.from("trade_in_receipts").delete().eq("id", receipt.id);
    return NextResponse.json({ error: itemsErr.message }, { status: 500 });
  }

  // Fetch complete receipt with items
  const { data: complete } = await supabase
    .from("trade_in_receipts")
    .select("*, trade_in_receipt_items(*)")
    .eq("id", receipt.id)
    .single();

  return NextResponse.json(complete, { status: 201 });
}
