export const SOMMER_BUNDLE_2026 = {
  id: "sommer-bundle-2026",
  /** Display name used across UI surfaces. */
  name: "Sommer Bundle",
  /** Inclusive start (Copenhagen time). */
  startsAt: new Date("2026-05-26T00:00:00+02:00"),
  /** Inclusive end (Copenhagen time, end of day). */
  endsAt: new Date("2026-06-30T23:59:59+02:00"),
  /** Existing Tempered Glass SKU id (one-size-fits-all). */
  glassSkuId: "0a718861-eae0-4c83-8cea-70d114a89fea",
  /** Retail price of the Tempered Glass in øre, used for strikethrough display. */
  glassRetailPriceOere: 15900,
  /** Retail price of the TPU cover in øre, used for strikethrough display. */
  tpuRetailPriceOere: 9900,
} as const;

/**
 * iPhone product_template id → clear TPU cover sku_product id.
 *
 * Generated by `scripts/audit-tpu-coverage.ts` on 2026-05-26.
 * Re-run that script after adding new iPhone templates and update this map.
 *
 * Note: iPhone 12 and iPhone SE (2020) are intentionally absent — their TPU
 * clear-case SKUs must be created in the admin UI before the bundle can ship
 * for those models. See docs/sommer-bundle-launch-blockers-2026-05-26.md.
 */
export const TPU_CASE_BY_TEMPLATE_ID: Record<string, string> = {
  "97993e88-508b-454d-a91f-e6f7775bbfb7": "d4212ece-02a6-426c-9ea8-7a6ba9ddd650", // Apple iPhone 11 Pro Max
  "66557c5f-54fa-4fc5-bb8e-55910be850c3": "cba33034-823a-435e-bc48-4d3eac950d98", // Apple iPhone 12 Pro
  "fcdf143a-389e-4e0b-8d47-f9c6074edf69": "63ae9412-131a-4428-852d-1a1063049d87", // Apple iPhone 13
  "49b05f85-4971-423f-bbd5-5470b3708cc5": "095833c2-5fc8-457a-89f1-22165ad375a2", // Apple iPhone 13 Pro
  "6f7d3b8c-a8fa-4ec8-985b-e27b6b2770e3": "8dae9e46-0d54-4c7d-8632-4c4fbd07e632", // Apple iPhone 13 Pro Max
  "ba80845e-1af0-40d5-9c00-439f1130219b": "d726a97d-c599-469d-b357-52113b753ac2", // Apple iPhone 14
  "7f437667-98ab-45ef-9d60-a1cadd9764ea": "8a0996dd-85e2-456b-b5d1-997cfec302cb", // Apple iPhone 14 Pro
  "2ac97ca1-0613-49c8-872c-25aab0402c46": "889f24e2-2f82-4474-8273-66b2ce14a78b", // Apple iPhone 14 Pro Max
  "9762d334-4481-4eea-8dc4-019997aca75e": "889f24e2-2f82-4474-8273-66b2ce14a78b", // Apple iPhone 14 Pro Max (eSIM Only)
  "736e3693-0496-4aa0-99f9-439810613221": "e9183739-49ad-41c2-9567-f9d019bda8bb", // Apple iPhone 15
  "8d07ae6f-3e21-495c-ad2a-b5105d7083ef": "c4bff159-a327-4e8a-b750-2c51a3103ee7", // Apple iPhone 15 Plus
  "8c6a8157-f6fa-4495-a52e-e98d87f552a1": "77bfd4bf-44a5-42a2-94fb-e4c2c32af3c8", // Apple iPhone 15 Pro
  "2872ddc5-377e-42b0-acb1-80d62ebfa787": "38470d3b-0a23-4850-9077-f94574e97846", // Apple iPhone 15 Pro Max
  "ef025415-5e1a-4c1f-903f-da40520e292f": "b55894ab-ceaa-4222-9751-319e7c0d517b", // Apple iPhone 16
  "46a9342d-0104-4a00-9237-6870ea8f77cd": "d6fbfbc7-4667-4c2b-ad0c-4754c7442ad4", // Apple iPhone 16 Plus
  "5ce397d5-cd2a-4084-80d8-10592550ac49": "3a69bbae-6ebd-4550-a7d4-1fc89501a060", // Apple iPhone 16 Pro
  "376f8d9f-3400-4aee-bcae-9d6db8ac8a3e": "ab3c041f-6d3a-423f-9d7f-95ab644501da", // Apple iPhone 16 Pro Max
  "4d477cf7-ba1f-43f2-8319-ae1948342da4": "f4d5a843-8ae5-4dd3-9894-50ed76ca68b5", // Apple iPhone 16e
  "5e01292f-4ebc-4340-96b8-4f9efe5cdcb4": "34959b4c-348e-4212-9d3d-7385b8d19933", // Apple iPhone 17
  "bca5ba79-c8bc-43a1-bbac-31c3f8112a73": "1a5fb18d-1b33-431a-9f0b-52d34663f460", // Apple iPhone 17 Air
  "163180b8-7d51-4e9f-af84-17cffd7267c5": "69164582-6a57-4e51-b08c-7b2288502f44", // Apple iPhone 17 Pro
  "7a475b31-1e78-4e1f-bb59-ff82d57055df": "425d8b86-6a52-45bf-b20a-b0123bc0d1a7", // Apple iPhone 17 Pro Max
};

export function isCampaignActive(now: Date = new Date()): boolean {
  return now >= SOMMER_BUNDLE_2026.startsAt && now <= SOMMER_BUNDLE_2026.endsAt;
}

export function getTpuCaseSkuId(templateId: string): string | null {
  return TPU_CASE_BY_TEMPLATE_ID[templateId] ?? null;
}

/** Battery upgrade pricing (separate concept from bundle, but lives in the same campaign module for cohesion). */
export const BATTERY_UPGRADE = {
  /** SKU-style identifier for the battery upgrade line item in Stripe. Not a real DB SKU; constructed at line-item build time. */
  kind: "battery-upgrade" as const,
  priceOere: 30000,
  /** Days the upgrade adds to shipping SLA. */
  shippingDelayLabel: "Forlænger levering til 2-4 dage",
} as const;
