-- Overførsler mellem butikker, del 1 af 3: tabeller og device-status 'in_transit'.
-- Kør FØR 20261004400100_stock_transfer_functions.sql og 20261004400200_stock_overview_view.sql.
--
-- Model: ét hoved (stock_transfers) med linjer (stock_transfer_lines). En linje er
-- enten en tilbehørs-/reservedelsvare (sku_product_id + antal), en konkret enhed
-- (device_id) eller en ANMODET enhedsgruppe (template_id + storage + grade + antal),
-- som afsenderen løser op til konkrete enheder når der sendes.
--
-- Lagerregel: varen står som "På vej" fra afsenderen markerer sendt til modtageren
-- scanner den. Tilbehør trækkes fra afsenderens sku_stock ved afsendelse (så det ikke
-- kan sælges nogen steder); enheder får status 'in_transit' (pos_create_sale og
-- webshoppens reservation kræver 'listed', så de kan ikke sælges). Modtageren får
-- varen ved modtagelse.
--
-- Antagelser om live-skemaet (verificér før kørsel, se spørgsmål nederst):
--   * locations, staff, sku_products, devices, stock_movements findes
--     (stock_movements fra 20261003120000_pos_foundation_tables.sql).
--   * Den gamle device_transfers-tabel (20260312_003) røres IKKE; den bliver ved med at
--     være historikken pr. enhed. transfer_receive skriver en række dér pr. modtaget enhed.
--
-- Idempotent og transaktionel.

BEGIN;

-- ============================================================
-- devices.status: tilføj 'in_transit', bevar alle eksisterende værdier.
-- Navnet på CHECK'en er ikke garanteret i prod, så den findes via definitionen.
-- ============================================================
DO $$
DECLARE c record;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.devices'::regclass AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%' AND pg_get_constraintdef(oid) ILIKE '%listed%'
  LOOP
    EXECUTE format('ALTER TABLE public.devices DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE public.devices DROP CONSTRAINT IF EXISTS devices_status_check;
ALTER TABLE public.devices ADD CONSTRAINT devices_status_check
  CHECK (status IN ('intake', 'graded', 'listed', 'reserved', 'sold', 'shipped', 'picked_up', 'returned', 'delisted', 'in_transit'));

-- ============================================================
-- stock_transfers
-- ============================================================
CREATE TABLE IF NOT EXISTS public.stock_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number integer GENERATED BY DEFAULT AS IDENTITY,
  from_location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE RESTRICT,
  to_location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'sent', 'received', 'cancelled')),
  note text,
  requested_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  sent_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,
  sent_at timestamptz,
  received_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,
  received_at timestamptz,
  cancelled_by uuid REFERENCES public.staff(id) ON DELETE SET NULL,
  cancelled_at timestamptz,
  cancel_reason text,
  closed_short boolean NOT NULL DEFAULT false,
  CHECK (from_location_id <> to_location_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS stock_transfers_number_key ON public.stock_transfers (number);
CREATE INDEX IF NOT EXISTS stock_transfers_status_to ON public.stock_transfers (to_location_id, status);
CREATE INDEX IF NOT EXISTS stock_transfers_status_from ON public.stock_transfers (from_location_id, status);
CREATE INDEX IF NOT EXISTS stock_transfers_requested_at ON public.stock_transfers (requested_at DESC);

-- ============================================================
-- stock_transfer_lines
--   qty           = anmodet antal
--   sent_qty      = antal afsenderen faktisk sendte (sættes ved afsendelse)
--   received_qty  = antal modtageren har scannet ind
--   returned_qty  = antal der er gået tilbage til afsenderen (mangler ved lukning, annullering)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.stock_transfer_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_id uuid NOT NULL REFERENCES public.stock_transfers(id) ON DELETE CASCADE,
  sku_product_id uuid REFERENCES public.sku_products(id) ON DELETE RESTRICT,
  device_id uuid REFERENCES public.devices(id) ON DELETE RESTRICT,
  template_id uuid,
  storage text,
  grade text,
  description text NOT NULL,
  qty integer NOT NULL CHECK (qty > 0),
  sent_qty integer NOT NULL DEFAULT 0 CHECK (sent_qty >= 0),
  received_qty integer NOT NULL DEFAULT 0 CHECK (received_qty >= 0),
  returned_qty integer NOT NULL DEFAULT 0 CHECK (returned_qty >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((sku_product_id IS NOT NULL)::int + (device_id IS NOT NULL)::int + (template_id IS NOT NULL)::int = 1),
  CHECK (device_id IS NULL OR qty = 1),
  CHECK (received_qty + returned_qty <= sent_qty)
);
CREATE INDEX IF NOT EXISTS stock_transfer_lines_transfer ON public.stock_transfer_lines (transfer_id);
CREATE INDEX IF NOT EXISTS stock_transfer_lines_sku ON public.stock_transfer_lines (sku_product_id) WHERE sku_product_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS stock_transfer_lines_device ON public.stock_transfer_lines (device_id) WHERE device_id IS NOT NULL;

-- Kun service-role (admin-API'erne). Ingen policies = ingen adgang for anon/authenticated.
ALTER TABLE public.stock_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_transfer_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.stock_transfers, public.stock_transfer_lines FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.stock_transfers, public.stock_transfer_lines TO service_role;

COMMIT;

-- Verifikation (forventet resultat i kommentar):
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--     WHERE conname = 'devices_status_check';                      -- indeholder 'in_transit' og 'delisted'
--   SELECT count(*) FROM information_schema.tables
--     WHERE table_name IN ('stock_transfers', 'stock_transfer_lines');  -- 2
